version: "3.9"

services:
  # ==========================
  # ZABBIX + PostgreSQL
  # ==========================
  postgres:
    image: postgres:15
    container_name: zabbix-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbixpass
      POSTGRES_DB: zabbix
    volumes:
      - ./zbx_pgdata:/var/lib/postgresql/data

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-6.4-latest
    container_name: zabbix-server
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbixpass
      POSTGRES_DB: zabbix
    ports:
      - "10051:10051"

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.4-latest
    container_name: zabbix-web
    restart: unless-stopped
    depends_on:
      - zabbix-server
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbixpass
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Europe/Moscow
    hostname: chat-service  
    ports:
      - "8080:8080"

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-6.4-latest
    container_name: zabbix-agent
    restart: unless-stopped
    depends_on:
      - zabbix-server
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_HOSTNAME: "chat-service"
    ports:
      - "10050:10050"

  # ==========================
  # PROMETHEUS
  # ==========================
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  # ==========================
  # GRAFANA
  # ==========================
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_data:/var/lib/grafana

  # ==========================
  # PostgreSQL для приложения
  # ==========================
  postgres_db:
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
      PGUSER: "postgres"
      PGPASSWORD: "pass"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - '54321:5432'
    volumes:
      - ./db-vol:/var/lib/postgresql/data

  # ==========================
  # Redis для приложения
  # ==========================
  redis_db:
    image: redis:latest
    restart: always
    environment:
      - REDIS_PORT=49153
      - REDIS_USER=default
      - REDIS_PASSWORD=redispw
    ports:
      - '49153:6379'

