global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'chat-service'
    static_configs:
      - targets: ['host.docker.internal:8070']

