version: "3.9"
services:
  grpc-service:
    build:
      context: .
      dockerfile: Dockerfile.grpc
    container_name: grpc-service
    ports:
      - "50051:50051"

  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - grpc-service
